CREATE TABLE CITAS(
	ID_CITA SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_USR SMALLINT NOT NULL,
    FECHA_CITA DATETIME,
    MOTIVO_CITA VARCHAR(255),
    STATUS_CITA VARCHAR(1) CHECK(STATUS_CITA IN ('1','2','3')), -- 1: pendiente, 2: cancelada, 3: finalizada
    ALTA_CITA TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY(ID_USR) REFERENCES USUARIOS(ID_USR) ON DELETE CASCADE ON UPDATE CASCADE -- Elimina las citas si el usuario es eliminado
);	-- Sin embargo, nosotros no eliminamos registros, los borrados son lógicos.

SELECT fecha_cita 
FROM CITAS 
WHERE fecha_cita LIKE '%2025-03-29%';

SELECT COUNT(*)
FROM CITAS
WHERE FECHA_CITA LIKE '%2025-03-29%';

SELECT FECHA_CITA
FROM CITAS
WHERE FECHA_CITA = '%2025-03-29%';


ALTER TABLE CITAS
MODIFY COLUMN MOTIVO_CITA VARCHAR(10);

ALTER TABLE CITAS
MODIFY COLUMN STATUS_CITA VARCHAR(1) NOT NULL DEFAULT '1',
ADD CONSTRAINT chk_status CHECK(STATUS_CITA IN ('1','2','3'));